### ISSUE TITLE
[Peer Review] Server Wiki API Call

### ISSUE THREAD

**Issue by mackenzieleach** [luuuk/screwthereview-server#24]
This comment should be addressed from Peer Review:

**I could build the software, following the provided instructions, on a machine matching the prerequisites mentioned in the instructions.**
-  "True, however, instructions in developer guide for server (in luuuk wiki) for API call to server or local development did not tell me how to make a search request. I tried adding /search?location=Seattle or something to the url but they do not work. It will be nice to show us an example Get request to show
us how to use it."

**Comment by luuuk** [comment]
Added an example call to the wiki
